### ISSUE TITLE
Train time

### ISSUE THREAD

**Issue by pcc-99** [wysnzzzz/DIT#1]
Great work, what is the training overhead, how long did it take, and how many GPUs were used

**Comment by wysnzzzz** [comment]
Thanks. We used 4 NVIDIA 3090Ti GPUs (24GB each) for the training. It took approximately 10 hours to complete 25 epochs.

**Comment by wysnzzzz** [comment]
> Great work, what is the training overhead, how long did it take, and how many GPUs were used

Thanks. We used 4 NVIDIA 3090Ti GPUs (24GB each) for the training. It took approximately 10 hours to complete 25 epochs.
