### ISSUE TITLE
关于mIoU指标与oIoU指标

### ISSUE THREAD

**Issue by WayneTomas** [wysnzzzz/DIT#3]
作者您好，感谢您的工作。请问refcoco/refcoco+/refcocog的mIoU指标可否全部公开呢？论文中只提到了refcoco上的mIoU具体数值

**Comment by wysnzzzz** [comment]
不好意思，单数据集的mIoU由于权重丢失，目前能找到并公开的仅有combine了refcoco,refcoco+,refcocog进行训练后的指标，所有的backbone均为ViT-B。在refcoco上,val77.01,testA78.55,testB74.86。在refcoco+上,val69.51,testA72.76,testB63.28。在refcocog上,val69.09,test69.90。

**Comment by WayneTomas** [comment]
感谢您的回复，您记录的这些指标对我们的研究有很大帮助，谢谢您。
