### ISSUE TITLE
SAM Text Prompting

### ISSUE THREAD

**Issue by jes-bro** [wysnzzzz/DIT#4]
How did you all get SAM baselines? I didn't think they released their text encoder.

**Comment by wysnzzzz** [comment]
As in the structure of the SAM paper, the text is extracted through the text encoder and input into the mask decoder as sparse prompt embedding.

**Comment by jes-bro** [comment]
Sounds good! I have another question. I'd like to use my own data with DIT, but I don't have bounding boxes, only masks and text descriptions. Do you all use the refcoco bounding boxes for anything? They seem to be extracted in the dataloader script and I was hoping I could not use bounding boxes.

**Comment by jes-bro** [comment]
I guess a better question is, how can I load my own data?

**Comment by wysnzzzz** [comment]
> Sounds good! I have another question. I'd like to use my own data with DIT, but I don't have bounding boxes, only masks and text descriptions. Do you all use the refcoco bounding boxes for anything? They seem to be extracted in the dataloader script and I was hoping I could not use bounding boxes.

Of course. DIT also doesn't use bounding box for training and inference, you can type [0.0, 0.0, 0.0, 0.0], ignore it.

**Comment by jes-bro** [comment]
Thanks! Another question. In the dataloader.py, I get an import error on line 33 import transformers. Where does that package come from? Also, truncate_seq_pair doesn't seem to be defined.

**Comment by jes-bro** [comment]
How can I visualize the masks?

**Comment by wysnzzzz** [comment]
> How can I visualize the masks?

Modify the config file LOG_IMAG to True, you can view it in tensorboard. If you need to save it, you may need to write some code in the test file.

**Comment by jes-bro** [comment]
What if I want to do inference on the images at full resolution?

**Comment by jes-bro** [comment]
Also, what are the mean and std in normalize and pad?

**Comment by wysnzzzz** [comment]
> 另外，归一化和垫的平均值和标准是什么？

You can find it on config file.

**Comment by wysnzzzz** [comment]
> Also, what are the mean and std in normalize and pad?

You can find it on config file.

**Comment by wysnzzzz** [comment]
> What if I want to do inference on the images at full resolution?

Please reshape it or write some code to deal with it.
