### ISSUE TITLE
Pre-trained DIT SAM Checkpoint

### ISSUE THREAD

**Issue by jes-bro** [wysnzzzz/DIT#5]
Hi there, do you have a checkpoint for DIT SAM pre-trained on refcoco? Thanks!

**Comment by wysnzzzz** [comment]
I will sort out and upload checkpoints as soon as possible. If you need it urgently, please give me the contact information, and I will give it to you by email or other means.

**Comment by wysnzzzz** [comment]
> Hi there, do you have a checkpoint for DIT SAM pre-trained on refcoco? Thanks!

I will sort out and upload checkpoints as soon as possible. If you need it urgently, please give me the contact information, and I will give it to you by email or other means.

**Comment by wysnzzzz** [comment]
We have uploaded our pre-trained checkpoint.
